def no_catching():
	try:
		print('Missing the except block')
	return 42
